<?php

require_once LIB_DIR . 'Response.php';

/**
 * Test class for Indextank_Response.
 * Generated by PHPUnit on 2011-05-24 at 11:14:05.
 */
class Indextank_ResponseTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Indextank_Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Indextank_Response(200, "ARGH");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function test_Contructor()
    {
        $this->assertEquals(200, $this->object->status);
        $this->assertEquals("ARGH", $this->object->response);
    }
}

?>
