<?php

require_once LIB_DIR . 'Api.php';

/**
 * Test class for Indextank_Api.
 * Generated by PHPUnit on 2011-05-24 at 11:18:52.
 */
class Indextank_ApiTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var Indextank_Api
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Indextank_Api('http://dummy');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    public function test_GetIndex()
    {
        $index = $this->object->get_index('test');
        $this->assertInstanceOf('Indextank_Index', $index);
    }
}
?>
